# Generated by Django 4.1 on 2022-08-28 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='child_comment',
        ),
    ]
