# Generated by Django 4.1 on 2022-09-02 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikePost',
        ),
    ]
