# Generated by Django 4.1 on 2022-09-03 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('message', '0002_remove_message_receiver_remove_message_room_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='meta',
        ),
        migrations.AddField(
            model_name='message',
            name='reciever',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='user.profile'),
        ),
        migrations.DeleteModel(
            name='MessageMeta',
        ),
    ]
