# Generated by Django 4.1 on 2022-09-03 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_remove_room_id_message_sender_room_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='reciever',
        ),
    ]
